$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline

name: ci_pipeline_component
display_name: Diabetes-Model-CI-Pipeline
description: Pipeline to train and evaluate a diabetes model
tags: { "devel_stage": "eval" }

inputs:
  model_name:
    type: string
    description: Name of the model to be registered
  dataset:
    type: mltable
    description: Dataset to be used for training and evaluation

outputs:
  train_data:
    type: uri_folder
    description: Training data
  test_data:
    type: uri_folder
    description: Test data
  validation_data:
    type: uri_folder
    description: Validation data
  trained_model:
    type: mlflow_model
    description: The trained MLflow model
  evaluation_output:
    type: uri_folder
    description: Evaluation output
  model_info_output_path:
    type: uri_folder
    description: Model info output path

jobs:
  split_mltable:
    type: command
    component: azureml:split_mltable@latest
    inputs:
      input_dataset: ${{parent.inputs.dataset}}
      random_seed: 42
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}
      validation_data: ${{parent.outputs.validation_data}}

  train:
    type: command
    component: azureml:train_model@latest
    inputs:
      train_data: ${{parent.jobs.split_mltable.outputs.train_data}}
    outputs:
      trained_model: ${{parent.outputs.trained_model}}

  evaluate_model:
    type: command
    component: azureml:evaluate_model@latest
    inputs:
      model_input: ${{parent.jobs.train.outputs.trained_model}}
      test_data: ${{parent.jobs.split_mltable.outputs.test_data}}
      model_name: ${{parent.inputs.model_name}}
    outputs:
      evaluation_output: ${{parent.outputs.evaluation_output}}

  register_model:
    type: command
    component: azureml:register_model@latest
    inputs:
      model_name: ${{parent.inputs.model_name}}
      model_path: ${{parent.jobs.train.outputs.trained_model}}
      evaluation_output: ${{parent.jobs.evaluate_model.outputs.evaluation_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
