$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline
experiment_name: Monitoring-Models-Experiment
display_name: Monitoring-Models-Experiment
description: CI example pipeline
tags: {'devel_stage': 'eval'}
settings:
  default_compute: azureml:d-cpu-ds12-v2

inputs:
  model_name: monitoring-diabetes-clr-mdl
  dataset: 
    path: azureml:diabetes-training:1
    type: uri_file

jobs:
  split_csv:
    type: command
    component: ../components/split_csv.yml
    inputs:
      input_file: ${{parent.inputs.dataset}}
      fraction: .8
      random_seed: 1
    outputs:
      output_file1:
        type: uri_file
      output_file2:
        type: uri_file
  train_and_register:
    type: command
    component: ../components/train_model.yml
    inputs:
      train_data: ${{parent.jobs.split_csv.outputs.output_file1}}
      test_data: ${{parent.jobs.split_csv.outputs.output_file2}}
      model_name: ${{parent.inputs.model_name}}
    outputs:
      trained_model:
        type: mlflow_model
