$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: cli-deployment-2

description: >-
  Deploy a diabetes classification model with custom logging to an online endpoint

tags: {"demo": "diabetes", "datacollection": "custom"}

endpoint_name: clr-diabetes-jhch-demo
model: azureml:monitoring-diabetes-clr-mdl:3
environment: azureml:diabetes-inference:2023-10-04-18:15:00
code_configuration:
  code: diabetes-deployment-custom
  scoring_script: score.py
instance_type: Standard_F2s_v2 # alternatives: Standard_DS3_v2, Standard_F2s_v2
instance_count: 1
app_insights_enabled: true

data_collector:
  rolling_rate: hour
  sampling_rate: 1
  collections:
    model_inputs:
      enabled: 'true'
      # data: azureml:diabetes-cli-deployment-inputs:1
    model_outputs:
      enabled: 'true'
      # data: azureml:diabetes-cli-deployment-outputs:1
    model_inputs_outputs:
      enabled: 'true'
      # data: azureml:diabetes-cli-deployment-inputs-outputs:1
