name: cd-triggered-by-aml-events
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  repository_dispatch:
    types: [model-registered-event]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set up environment
        run: |
          chmod +x setup.sh
          ./setup.sh
        working-directory: .github/cicd
        env:
          GROUP_PARAM: ${{ secrets.GROUP_PARAM }}
          LOCATION_PARAM: ${{ secrets.LOCATION_PARAM }}
          WORKSPACE_PARAM: ${{ secrets.WORKSPACE_PARAM }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      - name: deploy model
        run: |
          az ml online-endpoint update -f endpoints/online/endpoint/diabetes-endpoint.yml --resource-group $RESOURCE_GROUP_NAME --workspace-name $WORKSPACE_PARAM
          az ml online-deployment update -f endpoints/online/deployment/diabetes-deployment-custom.yml --resource-group $RESOURCE_GROUP_NAME --workspace-name $WORKSPACE_PARAM
        working-directory: pipelines
        env:
          GROUP_PARAM: ${{ secrets.GROUP_PARAM }}
          LOCATION_PARAM: ${{ secrets.LOCATION_PARAM }}
          WORKSPACE_PARAM: ${{ secrets.WORKSPACE_PARAM }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
