name: cd-triggered-by-aml-events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [model-registered-event]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: set up environment
        run: |
          chmod +x setup.sh
          ./setup.sh
        working-directory: .github/cicd
        env:
          GROUP_PARAM: ${{ secrets.GROUP_PARAM }}
          LOCATION_PARAM: ${{ secrets.LOCATION_PARAM }}
          WORKSPACE_PARAM: ${{ secrets.WORKSPACE_PARAM }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      - name: deploy model
        run: |
          az ml endpoint update -f endpoints/online/diabetes-endpoint.yml
          az ml online-deployment update -f endpoints/online/diabetes-deployment.yml
        working-directory: pipelines
